name: Step3Action

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ['Awesome Calculator CI build']
    types: [completed]

jobs:
  testing:
    name: download-artifact
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      actions: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Download artifact
        uses: actions/github-script@v6
        env:
          WORKFLOW_FILENAME: build-pipeline.yml
          ARTIFACT_NAME: awesome-calculator
          ARTIFACT_FILENAME: awesome-calculator.zip
          UNZIP_DIR: artifact
        with:
          script: |
            const script = require('./src/artifact_retrieval.js')
            await script({github, context, core})  