name: Step3Action

on: 
  workflow_dispatch:
  workflow_run:
    workflows: ['Awesome Calculator CI build']
    types: [completed]

jobs:
  step3_action:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.11"
    - name: Execute retrieval of artifact
      run: |
        import * as actionsGithub from '@actions/github';

const githubToken = actionsCore.getInput('token');

const artifacts = (await actionsGithub.getOctokit(githubToken).rest.actions.listArtifactsForRepo({
    owner: actionsGithub.context.repo.owner,
    repo: actionsGithub.context.repo.repo,
    name: 'manifest'
  })).data.artifacts;

        